{
	"version": 1620482075,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/2_0casespieces-sheet0.png",
		"images/2_0illupouvmode1-sheet0.png",
		"images/2_0illupouvmode2-sheet0.png",
		"images/2_0illutimer-sheet0.png",
		"images/2_0meilleurparcour-sheet0.png",
		"images/2_0minimap-sheet0.png",
		"images/2_0minimapjoueur-sheet0.png",
		"images/2_0minimapia1-sheet0.png",
		"images/2_0minimapia2-sheet0.png",
		"images/2_0minimapia3-sheet0.png",
		"images/2_0etoilespartic1.png",
		"images/2_0etoilespartic2.png",
		"images/2_0etoilespartic3.png",
		"images/2_0etoilespartic4.png",
		"images/2_0position-sheet0.png",
		"images/2_0commdash-sheet0.png",
		"images/2_0commgsaut-sheet0.png",
		"images/2_0commpsaut-sheet0.png",
		"images/2_0commtp-sheet0.png",
		"images/2_0dashselect-sheet0.png",
		"images/2_0dashselect-sheet1.png",
		"images/2_0focustpdash-sheet0.png",
		"images/2_0tpselect-sheet0.png",
		"images/2_0tpselect-sheet1.png",
		"images/2_0cubeeia1-sheet0.png",
		"images/2_0player-sheet0.png",
		"images/2_0spawn-sheet0.png",
		"images/2_0camera-sheet0.png",
		"images/2_0detecteuriaj-sheet0.png",
		"images/2_0boost.png",
		"images/2_0pieces-sheet0.png",
		"images/2_0pieces-sheet1.png",
		"images/2_0pieces-sheet2.png",
		"images/2_0effettp-sheet0.png",
		"images/2_0silhouette-sheet0.png",
		"images/2_0apeure-sheet0.png",
		"images/2_0rassure-sheet0.png",
		"images/2_0detetectordash-sheet0.png",
		"images/activatepower-sheet0.png",
		"images/2_0sylvia-sheet0.png",
		"images/2_0bosstrain-sheet0.png",
		"images/fin-sheet0.png",
		"images/2_0illucontr-sheet0.png",
		"images/2_0illupause-sheet0.png",
		"images/2_0illurestart-sheet0.png",
		"images/2_0illuquit-sheet0.png",
		"images/2_0illuson-sheet0.png",
		"images/2_0illuson-sheet1.png",
		"images/2_0pausebutton-sheet0.png",
		"images/2_0pausebutton-sheet1.png",
		"images/2_0illumusique-sheet0.png",
		"images/2_0illufx-sheet0.png",
		"images/2_0car1-sheet0.png",
		"images/2_0car2-sheet0.png",
		"images/2_0car4-sheet0.png",
		"images/2_0car3-sheet0.png",
		"images/2_0car5-sheet0.png",
		"images/2_0ween-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/2_0fondu-sheet0.png",
		"images/2_0introfont-sheet0.png",
		"images/2_0dialogfont-sheet0.png",
		"images/2_0next-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/returnhome-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/vnboutonmenu-sheet0.png",
		"images/2_1sylviadetecteurcollisionsdv-sheet0.png",
		"images/2_1sylvialiane-sheet0.png",
		"images/2_1sylviaparticles.png",
		"images/2_1sylviaronce-sheet0.png",
		"images/2_1sylviaspawnparticules-sheet0.png",
		"images/2_1sylviastun-sheet0.png",
		"images/2_1sylivadetecteurvide-sheet0.png",
		"images/2_1plantecarnivore-sheet0.png",
		"images/2_1liannedepine-sheet0.png",
		"images/2_1tmpicc1.png",
		"images/2_1tmsolc1.png",
		"images/2_7skinia011-sheet0.png",
		"images/2_7skinia011-sheet1.png",
		"images/2_7skinia011-sheet2.png",
		"images/2_7skinia012-sheet0.png",
		"images/2_7skinia012-sheet1.png",
		"images/2_7skinia012-sheet2.png",
		"images/2_7skinia013-sheet0.png",
		"images/2_7skinia013-sheet1.png",
		"images/2_7skinia013-sheet2.png",
		"images/2_7skinia021-sheet0.png",
		"images/2_7skinia021-sheet1.png",
		"images/2_7skinia021-sheet2.png",
		"images/2_7skinia022-sheet0.png",
		"images/2_7skinia022-sheet1.png",
		"images/2_7skinia022-sheet2.png",
		"images/2_7skinia023-sheet0.png",
		"images/2_7skinia023-sheet1.png",
		"images/2_7skinia023-sheet2.png",
		"images/2_7skinia041-sheet0.png",
		"images/2_7skinia041-sheet1.png",
		"images/2_7skinia041-sheet2.png",
		"images/2_7skinia042-sheet0.png",
		"images/2_7skinia042-sheet1.png",
		"images/2_7skinia042-sheet2.png",
		"images/2_7skinia043-sheet0.png",
		"images/2_7deethia01-sheet0.png",
		"images/2_7explosia01.png",
		"images/2_7traine02.png",
		"images/2_7deethia02-sheet0.png",
		"images/2_7traine04.png",
		"images/2_7deethia04-sheet0.png",
		"images/2_7skinia111-sheet0.png",
		"images/2_7skinia111-sheet1.png",
		"images/2_7skinia112-sheet0.png",
		"images/2_7skinia112-sheet1.png",
		"images/2_7skinia113-sheet0.png",
		"images/2_7skinia121-sheet0.png",
		"images/2_7skinia121-sheet1.png",
		"images/2_7skinia122-sheet0.png",
		"images/2_7skinia123-sheet0.png",
		"images/2_7skinia131-sheet0.png",
		"images/2_7skinia131-sheet1.png",
		"images/2_7skinia132-sheet0.png",
		"images/2_7skinia132-sheet1.png",
		"images/2_7skinia133-sheet0.png",
		"images/2_7skinia133-sheet1.png",
		"images/2_7skinia141-sheet0.png",
		"images/2_7skinia142-sheet0.png",
		"images/2_7skinia143-sheet0.png",
		"images/2_7skinia143-sheet1.png",
		"images/2_7traine11.png",
		"images/2_7deethia11-sheet0.png",
		"images/2_7traine12.png",
		"images/2_7traine00.png",
		"images/2_7deethjoueur0-sheet0.png",
		"images/2_7explosjoueur0.png",
		"images/2_7skin00-sheet0.png",
		"images/2_7skin00-sheet1.png",
		"images/2_7skin10-sheet0.png",
		"images/2_7skin20-sheet0.png",
		"images/2_7skin01-sheet0.png",
		"images/2_7skin11-sheet0.png",
		"images/2_7skin21-sheet0.png",
		"images/2_7skin21-sheet1.png",
		"images/2_7skin31-sheet0.png",
		"images/2_7skin31-sheet1.png",
		"images/2_7skin41-sheet0.png",
		"images/2_7skin51-sheet0.png",
		"images/2_7skin51-sheet1.png",
		"images/2_7skin51-sheet2.png",
		"images/2_7skin02-sheet0.png",
		"images/2_7skin12-sheet0.png",
		"images/2_7skin22-sheet0.png",
		"images/2_7skin32-sheet0.png",
		"images/2_7skin32-sheet1.png",
		"images/2_7skin42-sheet0.png",
		"images/2_7skin52-sheet0.png",
		"images/2_7skin52-sheet1.png",
		"images/2_7skin52-sheet2.png",
		"images/2_7skin03-sheet0.png",
		"images/2_7skin13-sheet0.png",
		"images/2_7skin23-sheet0.png",
		"images/2_7skin23-sheet1.png",
		"images/2_7skin33-sheet0.png",
		"images/2_7skin33-sheet1.png",
		"images/2_7skin43-sheet0.png",
		"images/2_7skin53-sheet0.png",
		"images/2_7skin53-sheet1.png",
		"images/2_7skin53-sheet2.png",
		"images/2_7skin04-sheet0.png",
		"images/2_7skin14-sheet0.png",
		"images/2_7skin24-sheet0.png",
		"images/2_7skin24-sheet1.png",
		"images/2_7skin34-sheet0.png",
		"images/2_7skin34-sheet1.png",
		"images/2_7skin44-sheet0.png",
		"images/2_7skin54-sheet0.png",
		"images/2_7skin54-sheet1.png",
		"images/2_7skin54-sheet2.png",
		"images/2_7skin05-sheet0.png",
		"images/2_7skin15-sheet0.png",
		"images/2_7skin25-sheet0.png",
		"images/2_7skin25-sheet1.png",
		"images/2_7skin35-sheet0.png",
		"images/2_7skin35-sheet1.png",
		"images/2_7skinboss03-sheet0.png",
		"images/2_7skinboss03-sheet1.png",
		"images/2_7skinboss05-sheet0.png",
		"images/2_7skinboss15-sheet0.png",
		"images/2_9bosstp-sheet0.png",
		"images/2_9onde-sheet0.png",
		"images/2_9rayon-sheet0.png",
		"images/2_9waypoint-sheet0.png",
		"images/sheet1-sheet0.png",
		"images/sheet2-sheet0.png",
		"images/sheet3-sheet0.png",
		"images/sheet4-sheet0.png",
		"images/sheet5-sheet0.png",
		"images/sheet6-sheet0.png",
		"images/2_9tmsolc1.png",
		"images/2_9tmpicc1.png",
		"images/sprite8-sheet0.png",
		"images/sprite8-sheet1.png",
		"images/tiledbackground.png",
		"images/tiledbackground10.png",
		"images/tiledbackground11.png",
		"images/tiledbackground12.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/tiledbackground5.png",
		"images/tiledbackground4.png",
		"images/tiledbackground7.png",
		"images/tiledbackground6.png",
		"images/tiledbackground9.png",
		"images/tiledbackground8.png",
		"images/1_1shinpixelred-sheet0.png",
		"images/1_1shinpixelgrey-sheet0.png",
		"images/1_5pointillearcs-sheet0.png",
		"images/1_5nuagestraining-sheet0.png",
		"images/1_5mer1training-sheet0.png",
		"images/1_5mer2training-sheet0.png",
		"images/1_5mer3training-sheet0.png",
		"images/1_5soltraining-sheet0.png",
		"images/1_5startcontinuetraining-sheet0.png",
		"images/1_5reviewtraining-sheet0.png",
		"images/1_5scorestraining-sheet0.png",
		"images/1_5fondtraining-sheet0.png",
		"images/1_5fondtraining-sheet1.png",
		"images/1_5fondtraining-sheet2.png",
		"images/1_5fondtraining-sheet3.png",
		"images/1_5fondtraining-sheet4.png",
		"images/1_5cubeerunnertraining-sheet0.png",
		"images/1_5cubeerunnertraining-sheet1.png",
		"images/1_5fondstoryrevsco-sheet0.png",
		"images/1_5fondstoryrevsco-sheet1.png",
		"images/1_5fondstoryrevsco-sheet2.png",
		"images/1_5fondstoryrevsco-sheet3.png",
		"images/1_5fondstory-sheet0.png",
		"images/1_5lunestory-sheet0.png",
		"images/1_5montagnesstory-sheet0.png",
		"images/1_5montagnesstory-sheet1.png",
		"images/1_5montagnesstory-sheet2.png",
		"images/1_5montagnesstory-sheet3.png",
		"images/1_5montagnesstory-sheet4.png",
		"images/1_5montagnesstory-sheet5.png",
		"images/1_5finalboss-sheet0.png",
		"images/1_5solcubeered-sheet0.png",
		"images/1_5cubeeredstory-sheet0.png",
		"images/1_5startcontinuestory-sheet0.png",
		"images/1_5reviewstory-sheet0.png",
		"images/1_5scoresstory-sheet0.png",
		"images/1_5particlesblanches.png",
		"images/1_5cubeered-sheet0.png",
		"images/1_5logo-sheet0.png",
		"images/1_5mycubee-sheet0.png",
		"images/1_5mycubee-sheet1.png",
		"images/1_5shop-sheet0.png",
		"images/1_5shop-sheet1.png",
		"images/1_5idcard-sheet0.png",
		"images/1_5parameter-sheet0.png",
		"images/1_5parameter-sheet1.png",
		"images/1_5storybouton-sheet0.png",
		"images/1_5fondpopups-sheet0.png",
		"images/1_5fondpopups-sheet1.png",
		"images/1_5fondpopups-sheet2.png",
		"images/1_5fondpopups-sheet3.png",
		"images/1_5backbouton-sheet0.png",
		"images/1_5trainingbouton-sheet0.png",
		"images/1_5solmenuprincipal-sheet0.png",
		"images/1_5selectionsskins-sheet0.png",
		"images/1_5resetbouton-sheet0.png",
		"images/1_5titremode-sheet0.png",
		"images/1_5illuaffichcomm-sheet0.png",
		"images/1_5switchparam-sheet0.png",
		"images/1_5rappelsousmode-sheet0.png",
		"images/1_5runbouton-sheet0.png",
		"images/1_5cubeeredmaprs-sheet0.png",
		"images/1_5cubeeredmaprs-sheet1.png",
		"images/1_5note-sheet0.png",
		"images/1_5note-sheet1.png",
		"images/1_5sousmodeswitch-sheet0.png",
		"images/1_5titrearc-sheet0.png",
		"images/1_5selectionarc-sheet0.png",
		"images/1_5fondpopupsmenuvn-sheet0.png",
		"images/1_5titrechap-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite11-sheet1.png",
		"images/sprite6-sheet0.png",
		"images/1_2illuconnexion-sheet0.png",
		"images/1_2localconnexion-sheet0.png",
		"images/1_2onlineconnexion-sheet0.png",
		"images/1_4particles.png",
		"images/1_4fondecrantitre-sheet0.png",
		"images/1_4cubeeredecrantitre-sheet0.png",
		"images/1_4ironcubeeecrantitre-sheet0.png",
		"images/1_4tapanywhere-sheet0.png",
		"images/onlinerankingbouton-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite14-sheet1.png",
		"images/transition-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite15-sheet1.png",
		"images/sprite15-sheet2.png",
		"images/sprite15-sheet3.png",
		"images/sprite16-sheet0.png",
		"images/sprite16-sheet1.png",
		"images/decorsmonde0-sheet0.png",
		"images/decorsmonde0-sheet1.png",
		"images/decorsmonde0-sheet2.png",
		"images/sprite17-sheet0.png",
		"images/decorschapter1act2-sheet0.png",
		"images/decorschapter1act2-sheet1.png",
		"images/decorschapter1act2-sheet2.png",
		"images/decorschapter1act3-sheet0.png",
		"images/decorschapter1act3-sheet1.png",
		"images/decorschapter1act3-sheet2.png",
		"images/decorschapter1act3-sheet3.png",
		"images/decorschapter1act3-sheet4.png",
		"images/decorschapter1act4-sheet0.png",
		"images/decorschapter1act4-sheet1.png",
		"images/decorschapter1act4-sheet2.png",
		"images/decorschapter1act5-sheet0.png",
		"images/decorschapter1act5-sheet1.png",
		"images/rotationdetector-sheet0.png",
		"images/fontvnchoice-sheet0.png",
		"images/fontvnchoice-sheet1.png",
		"images/fontvnchoice-sheet2.png",
		"images/fontvnchoice-sheet3.png",
		"images/fontvnchoice-sheet4.png",
		"images/sprite19-sheet0.png",
		"images/mom-sheet0.png",
		"images/alfred-sheet0.png",
		"images/jeremiah-sheet0.png",
		"images/william-sheet0.png",
		"images/sheet8-sheet0.png",
		"images/sheet9-sheet0.png",
		"images/sheet10-sheet0.png",
		"images/sheet11-sheet0.png",
		"images/sheet12-sheet0.png",
		"images/sheet13-sheet0.png",
		"images/sheet14-sheet0.png",
		"images/sheet15-sheet0.png",
		"images/sheet16-sheet0.png",
		"images/sheet17-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite24-sheet0.png",
		"images/soltrainningpart1-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/sheet23-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/panneauxaides-sheet0.png",
		"images/panneauxaides-sheet1.png",
		"images/tiledbackground13.png",
		"images/sprite27-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/2_9newrayonend-sheet0.png",
		"images/2_9newrayonend2-sheet0.png",
		"images/2_9newrayon.png",
		"images/2_9newrayon2.png",
		"images/2_0heure.png",
		"images/sprite35-sheet0.png",
		"media/sfx (vn apeure).m4a",
		"media/sfx (vn apeure).ogg",
		"media/sfx (vn choque).m4a",
		"media/sfx (vn choque).ogg",
		"media/sfx (vn determine).m4a",
		"media/sfx (vn determine).ogg",
		"media/sfx (vn pleure).m4a",
		"media/sfx (vn pleure).ogg",
		"media/sfx (vn s'enerve).m4a",
		"media/sfx (vn s'enerve).ogg",
		"media/sfx (vn suite text).m4a",
		"media/sfx (vn suite text).ogg",
		"media/sfx (annonce course vn).m4a",
		"media/sfx (annonce course vn).ogg",
		"media/sfx (back).m4a",
		"media/sfx (back).ogg",
		"media/sfx (fail_error) .m4a",
		"media/sfx (fail_error) .ogg",
		"media/sfx (normal) .m4a",
		"media/sfx (normal) .ogg",
		"media/sfx (pause).m4a",
		"media/sfx (pause).ogg",
		"media/sfx (touch final).m4a",
		"media/sfx (touch final).ogg",
		"media/sfx (page qui se tourne) .m4a",
		"media/sfx (page qui se tourne) .ogg",
		"media/sfx (whoosh transition).m4a",
		"media/sfx (whoosh transition).ogg",
		"media/sfx_switch_off.m4a",
		"media/sfx_switch_off.ogg",
		"media/sfx_switch_on.m4a",
		"media/sfx_switch_on.ogg",
		"media/sfx (dash).m4a",
		"media/sfx (dash).ogg",
		"media/sfx (depart course).m4a",
		"media/sfx (depart course).ogg",
		"media/sfx (grand saut).m4a",
		"media/sfx (grand saut).ogg",
		"media/sfx (petit saut).m4a",
		"media/sfx (petit saut).ogg",
		"media/sfx (piece).m4a",
		"media/sfx (piece).ogg",
		"media/sfx (slow motion).m4a",
		"media/sfx (slow motion).ogg",
		"media/sfx (tp).m4a",
		"media/sfx (tp).ogg",
		"media/sfx (victory) .m4a",
		"media/sfx (victory) .ogg",
		"media/sfx_death_v2.m4a",
		"media/sfx_death_v2.ogg",
		"media/sfx (success) .m4a",
		"media/sfx (success) .ogg",
		"media/chap0_boss3.m4a",
		"media/chap0_boss3.ogg",
		"media/chap0_boss5.m4a",
		"media/chap0_boss5.ogg",
		"media/chap0_ia.m4a",
		"media/chap0_ia.ogg",
		"media/chap0_vn.m4a",
		"media/chap0_vn.ogg",
		"media/chap0_revsco.m4a",
		"media/chap0_revsco.ogg",
		"media/chap1_boss5.m4a",
		"media/chap1_boss5.ogg",
		"media/chap1_ia.m4a",
		"media/chap1_ia.ogg",
		"media/chap1_vn.m4a",
		"media/chap1_vn.ogg",
		"media/chap1_revsco.m4a",
		"media/chap1_revsco.ogg",
		"media/ecran_daccueil_1_.m4a",
		"media/ecran_daccueil_1_.ogg",
		"media/login_cubee.m4a",
		"media/login_cubee.ogg",
		"media/menu_principal.m4a",
		"media/menu_principal.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"stylesheet.css",
		"upheavtt-webfont.woff",
		"upheavtt-webfont.woff2",
		"dialogue.xml"
	]
}